# Generated by Django 4.0.1 on 2022-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_payment_month_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month_is_paid',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
    ]
