# Generated by Django 4.0.1 on 2022-02-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_payment_month_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
    ]
